create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    slug varchar(140) not null unique,
    description text not null,
    price_cents integer not null,
    image_url varchar(500) not null,
    category varchar(80) not null,
    material varchar(80) not null,
    featured boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_products_slug on public.products (slug);
create index if not exists idx_products_featured on public.products (featured, id);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    status varchar(40) not null default 'pending',
    total_amount_cents integer not null,
    currency varchar(8) not null,
    stripe_session_id varchar(255),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_orders_status on public.orders (status);
create unique index if not exists idx_orders_stripe_session_id
    on public.orders (stripe_session_id)
    where stripe_session_id is not null;

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders (id) on delete cascade,
    product_id bigint not null references public.products (id),
    product_name varchar(120) not null,
    unit_amount_cents integer not null,
    quantity integer not null check (quantity > 0),
    image_url varchar(500) not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_order_items_order_id on public.order_items (order_id);
create index if not exists idx_order_items_product_id on public.order_items (product_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();
