create table if not exists public.collections (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    slug varchar(140) not null unique,
    description text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_collections_slug on public.collections (slug);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    slug varchar(140) not null unique,
    description text not null,
    price_cents integer not null,
    image_url varchar(500) not null,
    category varchar(80) not null,
    material varchar(80) not null,
    collection_id bigint references public.collections (id) on delete set null,
    featured boolean not null default false,
    in_stock boolean not null default true,
    stock_quantity integer not null default 1,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_products_slug on public.products (slug);
create index if not exists idx_products_featured on public.products (featured, id);
create index if not exists idx_products_collection_id on public.products (collection_id);

alter table public.products
add column if not exists in_stock boolean not null default true;

alter table public.products
add column if not exists stock_quantity integer not null default 1;

create table if not exists public.product_images (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products (id) on delete cascade,
    image_url varchar(500) not null,
    position integer not null default 0,
    is_primary boolean not null default false,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_product_images_product_id on public.product_images (product_id);
create index if not exists idx_product_images_position on public.product_images (product_id, position);

create table if not exists public.discount_codes (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    percent_off integer not null check (percent_off >= 1 and percent_off <= 100),
    active boolean not null default true,
    max_redemptions integer,
    redeemed_count integer not null default 0,
    starts_at timestamptz,
    expires_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_discount_codes_code on public.discount_codes (code);

insert into public.discount_codes (code, percent_off, active)
values ('4CCORD1', 10, true)
on conflict (code) do nothing;

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    status varchar(40) not null default 'pending',
    total_amount_cents integer not null,
    currency varchar(8) not null,
    discount_code varchar(80),
    discount_percent_off integer,
    discount_amount_cents integer not null default 0,
    stripe_session_id varchar(255),
    stripe_payment_intent_id varchar(255),
    customer_name varchar(255),
    customer_phone varchar(64),
    shipping_name varchar(255),
    shipping_line1 varchar(255),
    shipping_line2 varchar(255),
    shipping_city varchar(120),
    shipping_state varchar(120),
    shipping_postal_code varchar(40),
    shipping_country varchar(8),
    paid_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_orders_status on public.orders (status);
create unique index if not exists idx_orders_stripe_session_id
    on public.orders (stripe_session_id)
    where stripe_session_id is not null;

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders (id) on delete cascade,
    product_id bigint not null references public.products (id),
    product_name varchar(120) not null,
    unit_amount_cents integer not null,
    quantity integer not null check (quantity > 0),
    image_url varchar(500) not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_order_items_order_id on public.order_items (order_id);
create index if not exists idx_order_items_product_id on public.order_items (product_id);

create table if not exists public.stock_notifications (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products (id) on delete cascade,
    email varchar(255) not null,
    status varchar(40) not null default 'pending',
    created_at timestamptz not null default timezone('utc', now()),
    constraint uq_stock_notifications_product_email unique (product_id, email)
);

create index if not exists idx_stock_notifications_product_id on public.stock_notifications (product_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

drop trigger if exists collections_set_updated_at on public.collections;
create trigger collections_set_updated_at
before update on public.collections
for each row
execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

drop trigger if exists discount_codes_set_updated_at on public.discount_codes;
create trigger discount_codes_set_updated_at
before update on public.discount_codes
for each row
execute function public.set_updated_at();
