from datetime import datetime, timezone

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import sessionmaker

from app.core.config import settings
from app.db.base import Base
from app.models.collection import Collection
from app.models.discount_code import DiscountCode
from app.models.order import Order
from app.models.order_item import OrderItem
from app.models.product import Product
from app.models.product_image import ProductImage
from app.models.stock_notification import StockNotification

engine = create_engine(
    settings.database_url,
    connect_args={"check_same_thread": False} if settings.database_url.startswith("sqlite") else {},
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def seed_products() -> None:
    seed_data = [
        {
            "name": "Luna Pavé Ring",
            "slug": "luna-pave-ring",
            "description": "Anello con pavé luminoso e finitura dorata satinata.",
            "price_cents": 12900,
            "image_url": "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=80",
            "category": "Rings",
            "material": "Gold Vermeil",
            "featured": True,
        },
        {
            "name": "Aurora Tennis Bracelet",
            "slug": "aurora-tennis-bracelet",
            "description": "Bracciale elegante con zirconi e chiusura di sicurezza.",
            "price_cents": 18900,
            "image_url": "https://images.unsplash.com/photo-1601821765780-754fa98637c1?auto=format&fit=crop&w=900&q=80",
            "category": "Bracelets",
            "material": "Sterling Silver",
            "featured": True,
        },
        {
            "name": "Velvet Heart Charm",
            "slug": "velvet-heart-charm",
            "description": "Charm a cuore con smalto rosato pensato per composizioni modulari.",
            "price_cents": 5900,
            "image_url": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=80",
            "category": "Charms",
            "material": "Rose Gold",
            "featured": False,
        },
        {
            "name": "Sculpted Halo Earrings",
            "slug": "sculpted-halo-earrings",
            "description": "Orecchini a cerchio dal profilo scultoreo per look quotidiano.",
            "price_cents": 9900,
            "image_url": "https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=900&q=80",
            "category": "Earrings",
            "material": "Gold Plated",
            "featured": False,
        },
    ]

    db = SessionLocal()
    try:
        existing = db.query(Product).count()
        if existing:
            return
        for item in seed_data:
            db.add(Product(**item))
        db.commit()
    finally:
        db.close()


def seed_discount_codes() -> None:
    db = SessionLocal()
    try:
        existing = db.query(DiscountCode).filter(DiscountCode.code == "4CCORD1").first()
        if existing:
            return
        db.add(DiscountCode(code="4CCORD1", percent_off=10, active=True))
        db.commit()
    finally:
        db.close()


def ensure_schema_extensions() -> None:
    inspector = inspect(engine)
    tables = inspector.get_table_names()
    if "orders" not in tables:
        return

    existing_columns = {column["name"] for column in inspector.get_columns("orders")}
    product_columns = {column["name"] for column in inspector.get_columns("products")} if "products" in tables else set()
    dialect = engine.dialect.name
    timestamp_type = "TIMESTAMPTZ" if dialect == "postgresql" else "DATETIME"
    bigint_type = "BIGINT" if dialect == "postgresql" else "INTEGER"
    identity_primary_key = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if dialect == "postgresql"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    additions = {
        "stripe_payment_intent_id": "VARCHAR(255)",
        "customer_name": "VARCHAR(255)",
        "customer_phone": "VARCHAR(64)",
        "shipping_name": "VARCHAR(255)",
        "shipping_line1": "VARCHAR(255)",
        "shipping_line2": "VARCHAR(255)",
        "shipping_city": "VARCHAR(120)",
        "shipping_state": "VARCHAR(120)",
        "shipping_postal_code": "VARCHAR(40)",
        "shipping_country": "VARCHAR(8)",
        "paid_at": timestamp_type,
        "discount_code": "VARCHAR(80)",
        "discount_percent_off": "INTEGER",
        "discount_amount_cents": "INTEGER NOT NULL DEFAULT 0",
    }

    with engine.begin() as connection:
        if "discount_codes" not in tables:
            connection.execute(
                text(
                    f"""
                    CREATE TABLE discount_codes (
                        id {identity_primary_key},
                        code VARCHAR(80) NOT NULL UNIQUE,
                        percent_off INTEGER NOT NULL,
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        max_redemptions INTEGER,
                        redeemed_count INTEGER NOT NULL DEFAULT 0,
                        starts_at {timestamp_type},
                        expires_at {timestamp_type},
                        created_at {timestamp_type} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at {timestamp_type} NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            connection.execute(text("CREATE INDEX idx_discount_codes_code ON discount_codes (code)"))
        if "product_images" not in tables:
            connection.execute(
                text(
                    f"""
                    CREATE TABLE product_images (
                        id {identity_primary_key},
                        product_id {bigint_type} NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                        image_url VARCHAR(500) NOT NULL,
                        position INTEGER NOT NULL DEFAULT 0,
                        is_primary BOOLEAN NOT NULL DEFAULT FALSE,
                        created_at {timestamp_type} NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            connection.execute(text("CREATE INDEX idx_product_images_product_id ON product_images (product_id)"))
            connection.execute(text("CREATE INDEX idx_product_images_position ON product_images (product_id, position)"))
        for column_name, column_type in additions.items():
            if column_name in existing_columns:
                continue
            connection.execute(text(f"ALTER TABLE orders ADD COLUMN {column_name} {column_type}"))
        if "collection_id" not in product_columns:
            connection.execute(text(f"ALTER TABLE products ADD COLUMN collection_id {bigint_type}"))
        if "in_stock" not in product_columns:
            connection.execute(text("ALTER TABLE products ADD COLUMN in_stock BOOLEAN NOT NULL DEFAULT TRUE"))
        if "stock_quantity" not in product_columns:
            connection.execute(text("ALTER TABLE products ADD COLUMN stock_quantity INTEGER NOT NULL DEFAULT 1"))
        if "stock_notifications" not in tables:
            connection.execute(
                text(
                    f"""
                    CREATE TABLE stock_notifications (
                        id {identity_primary_key},
                        product_id {bigint_type} NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                        email VARCHAR(255) NOT NULL,
                        status VARCHAR(40) NOT NULL DEFAULT 'pending',
                        created_at {timestamp_type} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT uq_stock_notifications_product_email UNIQUE (product_id, email)
                    )
                    """
                )
            )
            connection.execute(text("CREATE INDEX idx_stock_notifications_product_id ON stock_notifications (product_id)"))


def create_order_record(
    *,
    email: str,
    currency: str,
    items: list[dict],
    total_amount_cents: int,
    discount_code: str | None = None,
    discount_percent_off: int | None = None,
    discount_amount_cents: int = 0,
) -> Order:
    db = SessionLocal()
    try:
        order = Order(
            email=email,
            status="pending",
            total_amount_cents=total_amount_cents,
            currency=currency,
            discount_code=discount_code,
            discount_percent_off=discount_percent_off,
            discount_amount_cents=discount_amount_cents,
        )
        db.add(order)
        db.flush()

        for item in items:
            db.add(
                OrderItem(
                    order_id=order.id,
                    product_id=item["product_id"],
                    product_name=item["name"],
                    unit_amount_cents=item["unit_amount_cents"],
                    quantity=item["quantity"],
                    image_url=item["image_url"],
                )
            )

        db.commit()
        db.refresh(order)
        return order
    finally:
        db.close()


def attach_stripe_session(*, order_id: int, stripe_session_id: str) -> None:
    db = SessionLocal()
    try:
        order = db.query(Order).filter(Order.id == order_id).first()
        if not order:
            return
        order.stripe_session_id = stripe_session_id
        db.commit()
    finally:
        db.close()


def mark_order_paid_from_checkout(
    *,
    order_id: int,
    stripe_session_id: str | None,
    stripe_payment_intent_id: str | None,
    customer_email: str | None,
    customer_name: str | None,
    customer_phone: str | None,
    shipping_name: str | None,
    shipping_line1: str | None,
    shipping_line2: str | None,
    shipping_city: str | None,
    shipping_state: str | None,
    shipping_postal_code: str | None,
    shipping_country: str | None,
) -> None:
    db = SessionLocal()
    try:
        order = db.query(Order).filter(Order.id == order_id).first()
        if not order:
            return
        was_already_paid = order.status == "paid"
        order.status = "paid"
        order.stripe_session_id = stripe_session_id or order.stripe_session_id
        order.stripe_payment_intent_id = stripe_payment_intent_id
        order.email = customer_email or order.email
        order.customer_name = customer_name
        order.customer_phone = customer_phone
        order.shipping_name = shipping_name
        order.shipping_line1 = shipping_line1
        order.shipping_line2 = shipping_line2
        order.shipping_city = shipping_city
        order.shipping_state = shipping_state
        order.shipping_postal_code = shipping_postal_code
        order.shipping_country = shipping_country
        order.paid_at = datetime.now(timezone.utc)
        if not was_already_paid:
            for item in order.items:
                product = db.query(Product).filter(Product.id == item.product_id).first()
                if not product:
                    continue
                product.stock_quantity = max(product.stock_quantity - item.quantity, 0)
                if product.stock_quantity == 0:
                    product.in_stock = False
        if order.discount_code and not was_already_paid:
            discount = db.query(DiscountCode).filter(DiscountCode.code == order.discount_code).first()
            if discount:
                discount.redeemed_count += 1
        db.commit()
    finally:
        db.close()


def mark_order_payment_failed(*, order_id: int, stripe_session_id: str | None) -> None:
    db = SessionLocal()
    try:
        order = db.query(Order).filter(Order.id == order_id).first()
        if not order:
            return
        order.status = "payment_failed"
        order.stripe_session_id = stripe_session_id or order.stripe_session_id
        db.commit()
    finally:
        db.close()


def mark_order_expired(*, order_id: int, stripe_session_id: str | None) -> None:
    db = SessionLocal()
    try:
        order = db.query(Order).filter(Order.id == order_id).first()
        if not order:
            return
        order.status = "expired"
        order.stripe_session_id = stripe_session_id or order.stripe_session_id
        db.commit()
    finally:
        db.close()
